FROM node:20-alpine3.18
LABEL version="1.0"

# Instalar dependencias necesarias
RUN apk update && apk upgrade && apk add --no-cache bash git openssh

# Establecer Zona horaria
ENV TZ=America/Santiago
RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# Crear usuario y grupo no-root
RUN addgroup react && adduser -S -G react react

# Instalar dependencias globales
RUN npm install -g @nestjs/cli
RUN npm install -g pnpm

# Establecer directorio de trabajo
WORKDIR /src

# Copiar archivos necesarios y ajustar permisos
COPY --chown=react:react package*.json pnpm-lock.yaml postcss.config.js tailwind.config.js vite.config.js index.html ./
RUN chown -R react:react /src

# Cambiar al usuario react
USER react

# Instalar dependencias de la app
RUN pnpm install

# Copiar el resto del código al contenedor
COPY --chown=react:react src ./src
COPY --chown=react:react public ./public

# Exponer puertos
EXPOSE 3000

# Comando por defecto
CMD ["pnpm", "dev"]
