FROM node:22-alpine3.22
LABEL version="1.0.0"

# Instalar dependencias necesarias
RUN apk update && apk upgrade && apk add --no-cache bash git openssh

# Establecer Zona horaria
ENV TZ=America/Santiago
RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# Instalar dependencias globales
RUN npm install -g @nestjs/cli
RUN npm install -g pnpm

# Establecer directorio de trabajo
WORKDIR /src

# Copiar archivos necesarios y ajustar permisos
COPY package*.json pnpm-lock.yaml postcss.config.js tailwind.config.js vite.config.js index.html ./

# Instalar dependencias de la app
RUN pnpm install

# Copiar el resto del código al contenedor
COPY src ./src
COPY public ./public

# Exponer puertos
EXPOSE 3000

# Comando por defecto
CMD ["pnpm", "dev"]
